name: Deploy Backend

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
      - '.github/workflows/backend-deploy.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: SSH deploy backend
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            set -e
            cd ~/sdlapps
            git fetch --all
            git checkout main
            git pull

            cd backend
            cat > .env << 'EOF'
            MONGO_URI=${{ secrets.MONGO_URI }}
            JWT_SECRET=${{ secrets.JWT_SECRET }}
            ADMIN_KEY=${{ secrets.ADMIN_KEY }}
            PORT=5001
            EOF

            npm ci --omit=dev

            if ! command -v pm2 >/dev/null 2>&1; then
              sudo npm i -g pm2
            fi

            if pm2 describe stvt-backend >/dev/null 2>&1; then
              pm2 reload stvt-backend
            else
              pm2 start server.js --name stvt-backend
            fi

            pm2 save
