name: Deploy Backend (self-hosted)

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
      - '.github/workflows/backend-deploy.yml'

jobs:
  deploy:
    runs-on: self-hosted
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Deploy backend locally (no SSH)
        working-directory: backend
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          ADMIN_KEY: ${{ secrets.ADMIN_KEY }}
        run: |
          set -e

          # Write .env from secrets
          cat > .env << 'EOF'
          MONGO_URI=${MONGO_URI}
          JWT_SECRET=${JWT_SECRET}
          ADMIN_KEY=${ADMIN_KEY}
          PORT=5001
          EOF

          # Install prod deps
          npm ci --omit=dev

          # Ensure pm2
          if ! command -v pm2 >/dev/null 2>&1; then
            sudo npm i -g pm2
          fi

          # Start/reload with pm2 using current working directory
          if pm2 describe stvt-backend >/dev/null 2>&1; then
            pm2 reload stvt-backend
          else
            pm2 start server.js --name stvt-backend
          fi

          pm2 save
