name: Deploy Backend

on:
  push:
    branches: [main]
    paths:
      - 'backend/**'
      - '.github/workflows/backend-deploy.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: tar -czf backend.tar.gz backend

      - uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: backend.tar.gz
          target: ~/sdlapps

      - uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            mkdir -p ~/sdlapps
            cd ~/sdlapps
            tar -xzf backend.tar.gz
            cd backend
            cp -n .env.example .env || true
            npm ci --omit=dev
            npx pm2 describe stvt-backend || npx pm2 start server.js --name stvt-backend
            npx pm2 reload stvt-backend
            npx pm2 save
