name: Deploy Backend (self-hosted)

on:
  push:
    branches: [ main ]
    paths:
      - "backend/**"

jobs:
  deploy:
    runs-on: [self-hosted, Linux, X64]

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Write .env
        run: |
          cat > .env << 'EOF'
          MONGO_URI=${{ secrets.MONGO_URI }}
          JWT_SECRET=${{ secrets.JWT_SECRET }}
          ADMIN_KEY=${{ secrets.ADMIN_KEY }}
          PORT=5001
          EOF

      - name: Install deps (prod)
        run: npm ci --omit=dev

      - name: Start/Reload PM2
        run: |
          if ! command -v pm2 >/dev/null 2>&1; then
            sudo npm i -g pm2
          fi
          pm2 describe stvt-backend >/dev/null 2>&1 && pm2 reload stvt-backend || pm2 start server.js --name stvt-backend
          pm2 save
