name: Deploy Frontend (self-hosted)

on:
  push:
    branches: [ main ]
    paths:
      - "frontend/**"

jobs:
  deploy:
    runs-on: [self-hosted, Linux, X64]

    defaults:
      run:
        working-directory: frontend

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Build
        run: |
          echo "REACT_APP_API_BASE=http://${{ secrets.EC2_HOST }}/api" > .env.production
          npm ci
          CI=false npm run build

      - name: Publish to Nginx
        run: |
          sudo mkdir -p /var/www/stvt
          sudo rsync -a --delete build/ /var/www/stvt/
          sudo nginx -t
          sudo systemctl reload nginx
