name: Deploy Frontend (self-hosted)

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-deploy.yml'

jobs:
  deploy:
    runs-on: self-hosted
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'frontend/package-lock.json'

      - name: Build frontend locally (no SSH)
        working-directory: frontend
        env:
          CI: "false"
        run: |
          set -e
          npm ci
          npm run build

      - name: Publish to web root
        run: |
          set -e
          sudo mkdir -p /var/www/stvt
          sudo rm -rf /var/www/stvt/*
          sudo cp -r frontend/build/* /var/www/stvt/
