name: Deploy Frontend

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-deploy.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: SSH build & publish frontend on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            set -e
            cd ~/sdlapps
            git fetch --all
            git checkout main
            git pull

            cd frontend
            npm ci
            CI=false npm run build

            sudo mkdir -p /var/www/stvt
            sudo rm -rf /var/www/stvt/*
            sudo cp -r build/* /var/www/stvt/
